### ISSUE TITLE
Apple TV (4th-generation or later)

### ISSUE THREAD

**Issue by ukmoose** [readeral/node-red-contrib-apple-tv#1]
Thanks for writing this. 
As the underlying library is for the 4th gen only is it worth amending your ReadMe to state this?

**Comment by readeral** [comment]
Great idea. FWIW, there hasn't been much takeup on this library yet that I can gather, so would really love any feedback you might have as new issues. I'd like to tighten it up if there are places it needs tightening (like further installation hiccups)
